### ISSUE TITLE
a question on cancel all open order

### ISSUE THREAD

**Issue by wj208** [SamSamhuns/ritpytrading#93]
*   ritpytrading version: 0.1.5
*   Python version: 3.7
*   Operating System: win10

Hi, when I try to cancel all my orders using cancel_all_open_orders(ses) in submit_cancel_orders, 
I got a Response [500]. And the response content is like b'{"code":"INTERNAL_SERVER_ERROR","message":"\xe6\x97\xa0\xe6\xb3\x95\xe5\x9c\xa8 System.Decimal \xe5\x92\x8c System.Decimal \xe4\xb8\x8a\xe6\x89\xa7\xe8\xa1\x8c\xe2\x80\x9cAnd\xe2\x80\x9d\xe6\x93\x8d\xe4\xbd\x9c\xe3\x80\x82"}'

If I use ses.post('http://localhost:9999/v1/commands/cancel?all=1'), it works well.
So, is there any bugs?

thanks

**Comment by SamSamhuns** [comment]
This issue should be resolved now.
